name: QA Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  cypress-tests:

    name: Cypress E2E Tests

    runs-on: ubuntu-24.04

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v7
        with:
          spec: cypress/e2e/spec.cy.js